INSERT INTO `questforchef`.`Roles` (`roleName`) VALUES ('Admin');
INSERT INTO `questforchef`.`Roles` (`roleName`) VALUES ('Regular user');
INSERT INTO `questforchef`.`Roles` (`roleName`) VALUES ('Cook');
INSERT INTO `questforchef`.`Roles` (`roleName`) VALUES ('Barman');
INSERT INTO `questforchef`.`Roles` (`roleName`) VALUES ('Manager');
INSERT INTO `questforchef`.`Roles` (`roleName`) VALUES ('Bidder');
INSERT INTO `questforchef`.`Users` (`email`, `enabled`, `firstName`, `lastName`, `password`, `tokenExpired`, `role_id`) VALUES ('milosa942@gmail.com', 1, 'Milos', 'Andric', 'pass', 1, '2');
INSERT INTO `questforchef`.`Users` (`email`, `enabled`, `firstName`, `lastName`, `password`, `tokenExpired`, `role_id`) VALUES ('miloso@gmail.com', 1, 'Milos', 'Obradovic', 'pass', 1, '1');
INSERT INTO `questforchef`.`Restaurants` (`address`, `desription`, `email`, `name`, `phone`, `rate`,`city`,`reon_num`,`open_hours`) VALUES ('Momcila Tapavice 18', 'Cl reduct malar/zygo fx', 'hgarrett3@ed.gov', 'Twitternation', '380-(257)526-4752', '4','Novi Sad','4','09-21h');
INSERT INTO `questforchef`.`Restaurants` (`address`, `desription`, `email`, `name`, `open_hours`, `phone`, `rate`,`city`,`reon_num`) VALUES ('Tihomira Ostojica 4', 'Local excis rectal les', 'mwoods4@mozilla.com', 'Brightbean', '08-20h', '348-(881)503-7377', '5','Novi Sad','4');
INSERT INTO `questforchef`.`Staff` (`birth_date`, `con_num`, `email`, `firstName`, `lastName`, `password`, `shoe_num`, `restaurant_id`, `role_id`) VALUES ('22-09-1994', 'XL', 'mladen@gmail.com', 'Mladen', 'Doslic', 'pass', '42', '1', '5');
INSERT INTO `questforchef`.`Staff` (`birth_date`,`email`, `firstName`, `lastName`, `password`, `shoe_num`, `restaurant_id`, `role_id`,`con_num`) VALUES ('22-09-1994','pera@gmail.com', 'Pera', 'Peric', 'pass', '34', '2', '5','L');
UPDATE `questforchef`.`Staff` SET `con_num`='cc' WHERE `id`='2';
